# Generated by Django 3.0.4 on 2020-03-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.IntegerField(max_length=10, verbose_name='کد کارگاه')),
                ('ContractRow', models.IntegerField(max_length=3, verbose_name='ردیف پیمان')),
                ('Name', models.CharField(max_length=24, verbose_name='نام کارگاه')),
                ('Client', models.CharField(max_length=30, verbose_name='نام کارفرما')),
                ('Address', models.CharField(max_length=40, verbose_name='آدرس کارگاه')),
                ('Ratio', models.CharField(max_length=2, verbose_name='نرخ حق بیمه')),
            ],
        ),
    ]
