# Generated by Django 3.0.4 on 2020-03-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workhouse',
            name='Code',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='کد کارگاه'),
        ),
        migrations.AlterField(
            model_name='workhouse',
            name='ContractRow',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='ردیف پیمان'),
        ),
        migrations.AlterField(
            model_name='workhouse',
            name='Ratio',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='نرخ حق بیمه'),
        ),
    ]
