# Generated by Django 3.0.4 on 2020-03-18 16:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200318_0033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workhouse',
            options={'verbose_name': ' ثبت کارگاه ', 'verbose_name_plural': ' ثبت کارگاه '},
        ),
        migrations.AlterField(
            model_name='workhouse',
            name='Code',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$', message='فقط عدد وارد شود')], verbose_name='کد کارگاه'),
        ),
        migrations.AlterField(
            model_name='workhouse',
            name='ContractRow',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{1,10}$', message='فقط عدد وارد شود')], verbose_name='ردیف پیمان'),
        ),
        migrations.AlterField(
            model_name='workhouse',
            name='Ratio',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^\\d{1,10}$', message='فقط عدد وارد شود')], verbose_name='نرخ حق بیمه'),
        ),
    ]
