# Generated by Django 3.0.4 on 2020-03-18 17:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200318_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BimehNum', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$', message='فقط عدد وارد شود')], verbose_name='شماره بیمه')),
                ('PersoneliNum', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$', message='فقط عدد وارد شود')], verbose_name='شماره پرسنلی')),
                ('LastName', models.CharField(max_length=30, verbose_name='نام خانوادگی')),
                ('FirstName', models.CharField(max_length=30, verbose_name='نام ')),
                ('DadName', models.CharField(max_length=30, verbose_name='نام پدر')),
                ('NationNum', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$', message='فقط عدد وارد شود')], verbose_name='کد ملی ')),
                ('IdNum', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$', message='فقط عدد وارد شود')], verbose_name='شماره شناسنامه')),
                ('IdPlace', models.CharField(max_length=10, verbose_name='محل صدور ')),
                ('BirthPlace', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$', message='فقط عدد وارد شود')], verbose_name='محل تولد ')),
                ('Sex', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$', message='فقط عدد وارد شود')], verbose_name='شماره ')),
                ('Nationality', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$', message='فقط عدد وارد شود')], verbose_name='شماره بیمه')),
                ('Job', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$', message='فقط عدد وارد شود')], verbose_name='شماره بیمه')),
            ],
        ),
    ]
