# Generated by Django 3.0.4 on 2020-03-24 15:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200323_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlist',
            name='month',
            field=models.CharField(max_length=2, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$', message='فقط عدد وارد شود')], verbose_name='ماه'),
        ),
        migrations.AddField(
            model_name='monthlist',
            name='year',
            field=models.CharField(max_length=2, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$', message='فقط عدد وارد شود')], verbose_name='سال'),
        ),
        migrations.CreateModel(
            name='DetailsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_days', models.SmallIntegerField()),
                ('daily_wage', models.BigIntegerField()),
                ('advantage', models.BigIntegerField()),
                ('month_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.MonthList', verbose_name='لیست ماهانه')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Workers', verbose_name=' نام کارگر')),
            ],
        ),
    ]
