# Generated by Django 3.0.4 on 2020-03-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200324_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailslist',
            options={'verbose_name': ' جزئیات لیست ', 'verbose_name_plural': ' جزئیات لیست '},
        ),
        migrations.AlterModelOptions(
            name='monthlist',
            options={'verbose_name': 'لیست ماهانه', 'verbose_name_plural': 'لیست ماهانه'},
        ),
        migrations.AlterModelOptions(
            name='workers',
            options={'verbose_name': 'کارکنان', 'verbose_name_plural': 'کارکنان'},
        ),
        migrations.AlterField(
            model_name='detailslist',
            name='advantage',
            field=models.BigIntegerField(verbose_name='مزایای ماهانه'),
        ),
        migrations.AlterField(
            model_name='detailslist',
            name='daily_wage',
            field=models.BigIntegerField(verbose_name='دستمزد روزانه'),
        ),
        migrations.AlterField(
            model_name='detailslist',
            name='working_days',
            field=models.SmallIntegerField(verbose_name='تعداد روز کارکرد'),
        ),
    ]
